name = "Propagators"
uuid = "b1384c70-1645-45b0-a82d-73c485533617"
authors = ["Mike Innes <mike.j.innes@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
